// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZjym32q4KXaVENAoZnEVs3NZLQkWbHM',
    appId: '1:188042720100:web:a2582fbfc4647431070071',
    messagingSenderId: '188042720100',
    projectId: 'currencyconverter-3ffbd',
    authDomain: 'currencyconverter-3ffbd.firebaseapp.com',
    storageBucket: 'currencyconverter-3ffbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPaFENHDI9iK7tK-CKzOkZRstkw26sBFU',
    appId: '1:188042720100:android:df5a163a6ee2a7ea070071',
    messagingSenderId: '188042720100',
    projectId: 'currencyconverter-3ffbd',
    storageBucket: 'currencyconverter-3ffbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKzaWSI1zYDv9hidAClUqXGJAWQwyfww',
    appId: '1:188042720100:ios:61ffadeac842c5f5070071',
    messagingSenderId: '188042720100',
    projectId: 'currencyconverter-3ffbd',
    storageBucket: 'currencyconverter-3ffbd.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVZjym32q4KXaVENAoZnEVs3NZLQkWbHM',
    appId: '1:188042720100:web:460f7c4bbc29cc0b070071',
    messagingSenderId: '188042720100',
    projectId: 'currencyconverter-3ffbd',
    authDomain: 'currencyconverter-3ffbd.firebaseapp.com',
    storageBucket: 'currencyconverter-3ffbd.firebasestorage.app',
  );
}
